"""Adiciona campo de curso ao usuario

Revision ID: fee9159ac650
Revises: 190f7b2aedf7
Create Date: 2026-06-04 21:28:04.087196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'fee9159ac650'
down_revision: Union[str, None] = '190f7b2aedf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('course', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'course')
    # ### end Alembic commands ###